name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Paso 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Paso 3: Run tests (unit + integration)
      - name: Run tests
        run: npm test

      # Paso 4: Build Docker image
      - name: Build Docker image
        run: docker build -t user/todo-list-api:latest .

      # Paso 5: Deploy to Heroku
      - name: Login to Heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Push Docker image to Heroku
        run: heroku container:push web --app nombre-de-tu-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Heroku App
        run: heroku container:release web --app nombre-de-tu-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
